include:
#    - ./services/compose-nginx.yaml
#    - ./services/compose-php.yaml
#    - ./services/compose-composer.yaml
#    - ./services/compose-mysql.yaml
#    - ./services/compose-mailhog.yaml
#    - ./services/compose-phpmyadmin.yaml
#    - ./services/compose-nodejs.yaml
#    - ./services/compose-apache2.yaml
#    - ./services/compose-clickhouse.yaml
#    - ./services/compose-elasticsearch.yaml
#    - ./services/compose-kibana.yaml
#    - ./services/compose-memcached.yaml
#    - ./services/compose-sphinx.yaml

networks:
    web-app:
        driver: bridge