services:
  apache2:
    build:
      context: ./etc/apache2
    container_name: ${APP_NAME}_apache2
    restart: always
    volumes:
      - ../etc/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ../etc/apache2/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ${APP_PATH}:/var/www/html
      - ../logs/apache2/:/usr/local/apache2/logs"
    ports:
      - 80:80
      - 443:443
    networks:
      - ${APP_NETWORK}