services:
  clickhouse:
    container_name: ${APP_NAME}_clickhouse
    image: yandex/clickhouse-server:21.8-alpine
    volumes:
        - ../.docker-volume-clickhouse:/var/lib/clickhouse
        - ../etc/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
        - ../etc/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    healthcheck:
        test: wget --spider -q 0.0.0.0:8123/ping
        interval: 5s
        timeout: 3s
        retries: 5
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    ports:
        - "8123:8123"
        - "9001:9000"