services:
  kibana:
    image: kibana:8.5.1
    container_name: kibana
    ports:
        - '${FORWARD_KIBANA_PORT:-5601}:5601'
    environment:
        SERVER_NAME: http://kibana.local
        ELASTICSEARCH_URL: '["http://elasticsearch:9200"]'
    networks:
      - ${APP_NETWORK}