services:
  nginx:
    build:
      context: ../etc/nginx
    container_name: ${APP_NAME}_nginx
    restart: always
    volumes:
      - .${APP_PATH}:/var/www/html
      - ../logs/nginx:/var/log/nginx
      - ../etc/nginx/bitrix.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '${HTTP_PORT:-80}:80'
      - '${HTTPS_PORT:-443}:443'
    depends_on:
      - phpfpm
    networks:
      - ${APP_NETWORK}